[package]
name = "fw-fanctrl-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
libc = "0.2.186"
serde = { version = "1.0.228", features = ["derive"] }
dirs = "5"
config = "0.15.25"
ron = "0.12.2"
env_logger = "0.11.11"
log = "0.4.33"
serde_json = "1.0.150"
lazy_static = "1.5.0"


[profile.release]
lto = "fat"
opt-level = 3
strip = true 
codegen-units = 1
debug = 0
debug-assertions = false
